apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: gfagundes/pedelogo-catalogo:v1
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        imagePullPolicy: Always
        env:
        - name: Mongo__Host
          value: "mongoservice.database.svc.cluster.local"
        - name: Mongo__User
          value: "mongouser"
        - name: Mongo__Password
          value: "mongopwd"
        - name: Mongo__Port
          value: "27017"
        - name: Mongo__DataBase
          value: "admin"
