apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongoexpress-deployment
spec:
  selector:
    matchLabels:
      app: mongoexpress
  template:
    metadata:
      labels:
        app: mongoexpress
    spec:
      containers:
      - name: mongoexpress
        image: mongo-express:1.0.0-alpha
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_SERVER
          value: mongodb.database.svc.cluster.local
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          value: mongouser
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          value: mongopwd

